command-executions:
  - trigger: expire # register, unregister, count, expire, add, remove, set
    execution-offset: -5 # minus value can be specified only for expire. ignored for count.
    target-permission:
      key: "test.use"
      context:
        world:
          - test1
          - test2
        othercontext: true
    player-permission: "timedperms.commandexecution.examplename"
    placeholder-requirement: # commands are executed only if this section pass.
      placeholder: "%placeholder-which-returns-boolean%"
      regex: ".*regexstring.*"
      more-than: 100 # placeholder return value should be number.
      less-than: 100 # placeholder return value should be number.

    command-source: console # or player
    commands:
      # placeholderapi placeholder is available if installed.
      # And target permission can also be specified (papi is not needed).
      - tell %player_name% test(%permission%)
