name: TimedPerms
version: '${projectVersion}'
main: net.okocraft.timedperms.Main
api-version: 1.19
commands:
  timedperms:
    aliases:
      - tperms
    description: "Command to set temporary permissions only which time passes a player is in game."
permissions:
  timedperms.use:
    default: op
